name: walleto
description: A new Flutter project.
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.0.1 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.6
  google_fonts: ^5.0.0
  outline_gradient_button: ^2.0.1+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/onboarding/
  fonts:
    - family: Avenir
      fonts:
        - asset: assets/fonts/Avenir Regular.ttf
